### ISSUE TITLE
No way to start your project locally

### ISSUE THREAD

**Issue by engineerKev** [msal4/royal_news#3]
Hi there,

I came across your article, it was great but it would have been better with a little more details on how to set up the project so it would run locally. I am here, post writing code, and I can't start my app. I am using nvm to change between node 8-10 and only on node v10 do I not get the error

`SyntaxError: Unexpected token import`

However on node 10 I get this error

`SyntaxError: Unexpected token {`

Your read has no mention of how set up the project locally and what version of node you might need or any needed, if there are any, auxiliary modules. Could you please include a set up step or a start command? I have been using 

`node index.js`

but that throws the errors I mentioned above. Sorry if I seem a bit agitated. I really liked your article, however; I lost my shit when I couldn't get it run locally and there was no mention of how to do that on your post or README. Again sorry, but please help me get this up and running. Thank you!

**Comment by msal4** [comment]
Hey there! this is a React Native Project so you would need:
- Android Studio or Xcode
- Node
- run `npm i` in the project directory.
now you can run `react-native run-android` or `react-native run-ios`  depending on your platform and it should work fine.
