### ISSUE TITLE
New Design for Royal News 

### ISSUE THREAD

**Issue by ghost** [msal4/royal_news#4]
Hi,

I'm designing for open source projects, expanding my portfolio. I want designing an icon for your project. There are a few ideas in my mind, I hope you accept and I do them. If you have an idea, please let me know. In this way we create a beautiful icon.

Best Regards.

**Comment by msal4** [comment]
Hi there!
For the icon I was thinking of something like medium's app icon
![](https://lh3.googleusercontent.com/qF9y0xIiYo_dk0JpryEl-lT2wJMDmz7groOBXqkalFg1SWPLklhuAUp0jIjoSLxDEi4=s180)
or this one from Beautiful Widget
![](https://lh3.ggpht.com/kQRUQ6WTCK22TmVFBSuidwMKXPB1G356-EmUocwW3VZVAjo3RuNnntGlRuE1UJ6UAg=s180)
a draft of how it would probably look like
![untitled](https://user-images.githubusercontent.com/30052233/40565155-68b8e462-6039-11e8-913d-30cf6818ee80.png)

but it doesn't have to be like it.
If you have a proposal it would be awesome to see and adjust it as we go.

**Comment by ghost** [comment]
![sunum](https://user-images.githubusercontent.com/36993664/40590629-7a8c1420-620a-11e8-9a93-548cd23e6af7.jpg)

Hi, I made a few examples for you. I used the newspaper letter and the initials of the program name.

**Comment by msal4** [comment]
Nice, well done!
I like the first and third one to the left.
Could you use light blue instead of red and make the first one where it says "rn" on the news paper with a blue highlight like the second one, also remove the newspaper but leave the text bellow the symbol.
Thanks.

**Comment by ghost** [comment]
![royal-news](https://user-images.githubusercontent.com/36993664/40681998-58e7e576-6393-11e8-9bab-b8b3e3d39bf9.jpg)

I made the changes you wanted. How does it look now?

**Comment by msal4** [comment]
They are amazing!
Fork the repo and add the icons with the .png extension in src>assets>icons (make a folder named icons in assets) then make a pull request.

**Comment by ghost** [comment]
thank you, I will send you PR today I hope you agree. If you need another design, you can contact me.

**Comment by ghost** [comment]
I send PR.
