### ISSUE TITLE
Add a new source for news

### ISSUE THREAD

**Issue by v0q1n8** [msal4/royal_news#9]
Hi, is it possible to use this code with another source for news? Thanks

**Comment by msal4** [comment]
It is, but it was meant as a simple tutorial for beginners. I don't recommend using it for production, it's possilbe tho.

**Comment by v0q1n8** [comment]
Thanks for your reply. Yes, of course, only for practice. Can I ask you what kind of link it is possible to use in this code with other sources? I tried different one but it doesn't work.

**Comment by msal4** [comment]
no problem, you have to update the code in order to use it with other sources, as I said it was meant as a tutorial and I wrote it a long time ago.
